language: objective-c
osx_image: xcode8.2

cache:
    timeout: 300
    bundler: true
    cocoapods: true
    directories:
        - vendor/bundle

before_install:
    - export LANG=en_US.UTF-8
    # pre-starting the simulator
    - xcrun instruments -w "iPhone 7 (10.2) [E40727B3-41FB-4D6E-B4CB-BFA87109EB12]" || true
    # fetching all data
    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
    # removing cashed tags
    - git tag -l | xargs git tag -d
    - git fetch --tags

install:
    - gem update bundler
    - bundle install --path vendor/bundle # to cache vendor/bundle
    - bundle exec pod update

before_script:
    - "$APP_NAME/Scripts/add-key.sh"

script:
    #- travis_wait 10 $APP_NAME/Scripts/test.sh
    - travis_wait 10 $APP_NAME/Scripts/sign-and-upload.sh staging

#before_cache:
    #- somescript.sh

#after_success:
    #- somescript.sh

#after_failure:
    #- somescript.sh

#before_deploy:
    #- somescript.sh

deploy:
    provider: script
    script: travis_wait 30 $APP_NAME/Scripts/sign-and-upload.sh $DEVELOP_LANE
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
        branch: $DEVELOP_BRANCH
        tags: true

deploy:
    provider: script
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    script: travis_wait 30 $APP_NAME/Scripts/sign-and-upload.sh $RELEASE_LANE
    on:
        branch: $RELEASE_BRANCH
        tags: true

#after_deploy:
    #- somescript.sh

after_script:
    - "$APP_NAME/Scripts/remove-key.sh"

notifications:
    #hipchat:
        #rooms: XXX
        #template:
            #- '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
            #(<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
            #format: html
    email:
        recipients:
            - vladimir.goncharov@flatstack.com
        on_success: always
        on_failure: always
